spring:
  datasource:
    url: jdbc:postgresql://172.16.2.130:54333/postgres
    username: pgvector
    password: pgvector
  ai:
    vectorstore:
      pgvector:
        dimensions: 768
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        model: qwen:0.5b
      embedding:
        model: mofanke/dmeta-embedding-zh:latest
# springdoc-openapi项目配置`
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bxmdm.ai.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn